---
name: Update version

on:
  push:
    branches:
      - main

jobs:
  update-version:
    if: github.repository_owner == 'pidgin'
    name: update-version
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Prepare build environment
        run: |
          sudo apt-get update -yy
          sudo apt-get install -yy --no-install-recommends \
            meson
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683  # v4.2.2
      - name: Update version
        run: |
          meson rewrite kwargs set project / version `date +%Y-%m-%d-${GITHUB_SHA}`
      - name: Commit version
        uses: stefanzweifel/git-auto-commit-action@b863ae1933cb653a53c021fe36dbb774e1fb9403 #  v5.2.0
        with:
          commit_user_name: Pidgy
          commit_user_email: pidgy@pidgin.im
          commit_message: Automatic version update
